const types = {
    // Clothes
    CLOTHES_CLASS_UPDATE: "CLOTHES_CLASS_UPDATE",
    CLOTHES_CUT_UPDATE: "CLOTHES_CUT_UPDATE",
    CLOTHES_PROP_UPDATE: "CLOTHES_PROP_UPDATE",
    CLOTHES_POST: "CLOTHES_POST",
    // CurrentNode
    CURRENT_NODE_UPDATE: "CURRENT_NODE_UPDATE",
};

export default types;
